ALTER TABLE players DROP COLUMN IF EXISTS user_id;

ALTER TABLE users DROP COLUMN IF EXISTS role_id;

DROP TABLE IF EXISTS roles_permissions;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS permissions;
